create table if not exists public.data_change_audit (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  table_schema text not null,
  table_name text not null,
  operation text not null,
  row_data jsonb,
  statement_details jsonb,
  txid bigint not null default txid_current(),
  actor_current_user text not null default current_user,
  actor_session_user text not null default session_user,
  application_name text,
  client_addr inet
);

create index if not exists idx_data_change_audit_occurred_at
  on public.data_change_audit (occurred_at desc);

create index if not exists idx_data_change_audit_table
  on public.data_change_audit (table_schema, table_name, occurred_at desc);

alter table public.data_change_audit enable row level security;

create or replace function public.audit_deleted_row()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.data_change_audit (
    table_schema,
    table_name,
    operation,
    row_data,
    statement_details,
    application_name,
    client_addr
  )
  values (
    tg_table_schema,
    tg_table_name,
    tg_op,
    to_jsonb(old),
    jsonb_build_object(
      'trigger_name', tg_name
    ),
    current_setting('application_name', true),
    inet_client_addr()
  );

  return old;
end;
$$;

create or replace function public.audit_truncate_statement()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.data_change_audit (
    table_schema,
    table_name,
    operation,
    row_data,
    statement_details,
    application_name,
    client_addr
  )
  values (
    tg_table_schema,
    tg_table_name,
    tg_op,
    null,
    jsonb_build_object(
      'trigger_name', tg_name
    ),
    current_setting('application_name', true),
    inet_client_addr()
  );

  return null;
end;
$$;

drop trigger if exists audit_cases_delete on public.cases;
create trigger audit_cases_delete
after delete on public.cases
for each row execute function public.audit_deleted_row();

drop trigger if exists audit_cases_truncate on public.cases;
create trigger audit_cases_truncate
after truncate on public.cases
for each statement execute function public.audit_truncate_statement();

drop trigger if exists audit_suspects_delete on public.suspects;
create trigger audit_suspects_delete
after delete on public.suspects
for each row execute function public.audit_deleted_row();

drop trigger if exists audit_suspects_truncate on public.suspects;
create trigger audit_suspects_truncate
after truncate on public.suspects
for each statement execute function public.audit_truncate_statement();

drop trigger if exists audit_players_delete on public.players;
create trigger audit_players_delete
after delete on public.players
for each row execute function public.audit_deleted_row();

drop trigger if exists audit_players_truncate on public.players;
create trigger audit_players_truncate
after truncate on public.players
for each statement execute function public.audit_truncate_statement();

drop trigger if exists audit_game_events_delete on public.game_events;
create trigger audit_game_events_delete
after delete on public.game_events
for each row execute function public.audit_deleted_row();

drop trigger if exists audit_game_events_truncate on public.game_events;
create trigger audit_game_events_truncate
after truncate on public.game_events
for each statement execute function public.audit_truncate_statement();
